---
- name: install dev tools
  yum:
    name: "@Development tools"
    state: present

- name: install x86 oracle dependencies for 11g
  yum:
    state: latest
    name: "{{ oracle_packages }}"
    disable_gpg_check: yes


    #- name: install x86 oracle bi packages
    #  yum:
    #    state: present
    #    name: "{{ oracle_bi_packages }}"
    #
    #
