---
- name: Create Users
  user:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    state: "present"
    password: "{{ password | default(omit) }}"
    shell: "{{ item.value.shell |default('/bin/bash')}}"
    group: "{{ item.value.group | default(omit) }}"
    home: "{{ item.value.home | default(omit) }}"
    update_password: "{{ update_pwd | default(omit) }}"
    comment: "{{ item.value.com | default(omit) }}"
    createhome: "{{ createhome | default(omit) }}"
    non_unique: "{{ non_unique | default(omit) }}"
    local: yes
  with_dict: "{{ users_list | default({}) }}"

- name: Add secondary groups to users
  user:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    append: yes
    state: "present"
    groups: "{{ item.value.groups | default(omit) }}"
  with_dict: "{{ users_list | default({}) }}"
