---
- name: Config bash profile
  blockinfile:
     path: /home/oracle/.bashrc
     block: "{{ bashconfig }}"

- name: Set authorized key without validating the TLS/SSL certificates
  authorized_key:
    user: "{{ item.value.user }}"
    state: present
    path: "{{ item.value.path | default(omit) }}"
    key: "{{ item.value.key }}"
    validate_certs: False
  with_dict: "{{ keys_list | default({}) }}"

